$ErrorActionPreference = "Stop"

$repoRoot = Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..")
$hash = (& git -C $repoRoot.Path rev-parse --short=8 HEAD 2>$null).Trim()
if (-not $hash) {
  $hash = "unknown"
}

$versionFile = Join-Path $repoRoot.Path "js/version.js"
$content = @"
/**
 * Generated by scripts/update-version.ps1.
 * Do not edit manually.
 */
export const COMMIT_HASH = "$hash";
"@

$encoding = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($versionFile, $content, $encoding)
